kind: Service
apiVersion: v1
metadata:
  name: fraud
  labels:
    app: fraud
spec:
  ports:
    - name: 9080-tcp
      protocol: TCP
      port: 9080
      targetPort: 9080
    - name: 9443-tcp
      protocol: TCP
      port: 9443
      targetPort: 9443
  type: ClusterIP
  sessionAffinity: None
  selector:
    deployment: fraud
