kind: Service
apiVersion: v1
metadata:
  name: loadgenerator
  labels:
    app: loadgenerator
spec:
  ports:
    - name: 8000-tcp
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
  sessionAffinity: None
  selector:
    deployment: loadgenerator
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: loadgenerator
  labels:
    app.kubernetes.io/component: http
    app.kubernetes.io/instance: loadgenerator
    app.kubernetes.io/name: loadgenerator
    release: loadgenerator
spec:
  to:
    kind: Service
    name: loadgenerator
    weight: 100
  port:
    targetPort: 8000-tcp
  wildcardPolicy: None
